# Generated by Django 5.0.6 on 2024-05-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
